### ISSUE TITLE
Add support for Switcher devices

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#13]
[Switcher](https://switcher.co.il/) creates smart devices and most famously known for their Boiler products.
Percent of users in [Home Assistant lass than 1%](https://www.home-assistant.io/integrations/switcher_kis/).

![image](https://user-images.githubusercontent.com/9304740/126871831-fafa31f9-e0f6-4a76-81b5-58005c4920ab.png)

**Comment by guyluz11** [comment]
Python script to control swticher devices [Switcher-V2-Python](https://github.com/NightRang3r/Switcher-V2-Python) used by [homebridge](https://www.npmjs.com/package/homebridge-switcher-platform) also check [homebridge-switcher-platform](https://github.com/nitaybz/homebridge-switcher-platform).
JavaScript port of the Switcher-V2-Python lib can be found [here](https://github.com/johnathanvidu/switcher-js).

Found also another Python [pyswitcherv2](https://github.com/sagilo/pyswitcherv2)

**Comment by chena-1** [comment]
let's work on it together @guyluz11

**Comment by Tamir198** [comment]
I can help with that as well, I want to join in if possible

**Comment by guyluz11** [comment]
Sure @Tamir198, we will be glad.

@chena-1  lets decide in discord when to seat on this together and reverse engineer [this one](https://github.com/nitaybz/homebridge-switcher-platform) as I think it support the largest range of devices.

**Comment by guyluz11** [comment]
Thanks to both of you @chena-1 and @Tamir198, we are now have added support for switcher devices.

Thank you a lot and will see you in the next issue 😁.
