### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#175]
Please update all project dependencies to the last version.

If the project gets compiled I will probably accept the pr.

**Comment by superiorsd10** [comment]
@guyluz11 Hey! Can I work on this issue?

**Comment by guyluz11** [comment]
@superiorsd10 Sure :)

**Comment by superiorsd10** [comment]
@guyluz11 I just wanna ask if I'm allowed to update the `sdk version` also (incase if any dependency requires the latest `sdk version`).

![SCR-20220929-qhg](https://user-images.githubusercontent.com/92971894/193046414-685be046-c639-4d72-95c9-d2ee088466f9.png)

**Comment by guyluz11** [comment]
Yes feel free to update it as well

**Comment by superiorsd10** [comment]
@guyluz11 Okay! Thanks a lot!

**Comment by guyluz11** [comment]
Pr got merged, thanks @superiorsd10 will now close the issue

**Comment by superiorsd10** [comment]
@guyluz11 You're most welcome :) Also, thanks for guiding me through problems on this issue.
