### ISSUE TITLE
Ignore file in git action dart format

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#182]
As you can see the git action format did a format on `lib/injection.config.dart`
https://github.com/CyBear-Jinni/cbj_hub/pull/181/commits/b66e3c137c19a185ffec6c4f320371369169a7ec

`injection.config.dart` is autogenerated file and thus should not get formatted.

Please change git action dart format so that it will ignore `lib/injection.config.dart`

https://github.com/CyBear-Jinni/cbj_hub/blob/4e84ecab6be5570a05d0520200c348956187950d/.github/workflows/format.yml#L29

Should become

`find . -name "*.dart" ! -path '*/gen/*' ! -name 'injection.config.dart' | tr '\n' ' ' | xargs dart format`

**Comment by drishtigehi** [comment]
Hi, I would like to work on this issue, kindly assign it to me

**Comment by guyluz11** [comment]
It is now yours @drishtigehi

**Comment by bilal-aamer** [comment]
Hey @guyluz11, Could you assign this issue to me as well. Thanks

**Comment by guyluz11** [comment]
This issue already assigned to someone else 

> Hey @guyluz11, Could you assign this issue to me as well. Thanks

**Comment by drishtigehi** [comment]
kindly review https://github.com/CyBear-Jinni/cbj_hub/pull/196 @guyluz11

**Comment by guyluz11** [comment]
Hi @drishtigehi I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by guyluz11** [comment]
Updating readme with the new line it should be replaced with

**Comment by guyluz11** [comment]
Closing as it got merged
