### ISSUE TITLE
Readme is missing NodeRED instructions

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#188]
In the [readme](https://github.com/CyBear-Jinni/cbj_hub/blob/dev/README.md) file we are missing NodeRed installation instructions + link.

Please add node-red instructions under the MQTT with the following link

NodeRed link: https://snapcraft.io/node-red

MQTT broker link: https://snapcraft.io/mosquitto 

![image](https://user-images.githubusercontent.com/9304740/193888120-7e7be109-f49d-43fb-8971-5108e968304b.png)

The end result should look like this (with links)

> To run the hub you will also need MQTT broker as well as NodeRed.

**Comment by Mitternachtsmond** [comment]
I will do it
Assign it to me @guyluz11

**Comment by guyluz11** [comment]
Thanks.

PR got merged, will close the issue now.
