### ISSUE TITLE
Readme change social media icons

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#189]
Please change the social media icons to be the same as the one in the bottom of this readme

https://github.com/CyBear-Jinni/cbj_app/blob/dev/README.md

**Comment by Ishika414** [comment]
I would like to work on this issue.

**Comment by guyluz11** [comment]
You got it @Ishika414

**Comment by bilal-aamer** [comment]
Hey @guyluz11 could I address this issue!

**Comment by guyluz11** [comment]
> Hey @guyluz11 could I address this issue!

This issue already assigned to someone else

**Comment by guyluz11** [comment]
Pr got merged 
Will close issue now 
Thanks
