### ISSUE TITLE
Make a professional diagram out of an existing one

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#19]
The concept of how the code of the Hub is being divided is not so clear at first glance.

I created the diagram but it should be remarked to look more professional.

![CBJ Hub diagram](https://user-images.githubusercontent.com/9304740/127879736-0b9de144-aa23-49bc-84b4-39b26e6f8bc0.png)

**Comment by Mitternachtsmond** [comment]
@guyluz11 Can I do this issue under the hacktoberfest?

**Comment by guyluz11** [comment]
Yes but I am not sure how to commit to Wiki works

> @guyluz11 Can I do this issue under the hacktoberfest?

The current diagram is located here
https://github.com/CyBear-Jinni/cbj_hub/wiki/Coding-guidelines

I am not sure how can it count for you as I am not sure if commits to Wiki can go through pr request.

**Comment by Mitternachtsmond** [comment]
Page does not exist @guyluz11

**Comment by guyluz11** [comment]
https://github.com/CyBear-Jinni/cbj_hub.wiki.git

![Screenshot_20221005-012439_Firefox](https://user-images.githubusercontent.com/9304740/193941419-1f78e622-6c1f-4a91-a4b8-b25c2047725b.jpg)

This is what I get for copying the bottom url

**Comment by Mitternachtsmond** [comment]
I will make a diagram and if it's accepted by you @guyluz11 
You can add hacktoberfest-accepted label if you approve it

**Comment by guyluz11** [comment]
I can add hacktoberfest-accepted lable to this issue.

Is that what you meant?

**Comment by BornToSucceed** [comment]
If the diagram I approve is accepted by you then you can add the hacktoberfest-accepted lable to the PR

**Comment by Mitternachtsmond** [comment]
If the diagram I make is accepted by you then you can add the hacktoberfest-accepted label to the PR

**Comment by guyluz11** [comment]
Hi @Mitternachtsmond I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks

**Comment by guyluz11** [comment]
Most of the Hub functionality had moved to cbj_integrations_controller to allow use in the Hub and the App.
So the architecture moved as well, here is a link to it
https://github.com/CyBear-Jinni/cbj_integrations_controller/wiki
