### ISSUE TITLE
Update injectable to new version

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#270]
The new version of injectable configures `getIt` differently.

Let's update it to the last version

**Comment by SankethBK** [comment]
@guyluz11 what are the changes, couldn't find it in changelog

**Comment by guyluz11** [comment]
We prefer to have the last version of all packages if possible, the change to the new injectable version require some changes so I left it for later.

Do you mean what time the changes in the new injectable version?

**Comment by SankethBK** [comment]
Yes, I have used get_it before, I am not familiar with get_it scopes, are we using it here. Also should we use the new decorators?

**Comment by guyluz11** [comment]
I'm not sure what is get it Scopes so probably not.

Just updating the packages and checking that it is compiling.
Yes, let's also use the new decorators.

**Comment by guyluz11** [comment]
Pr Marged, closing issue
