### ISSUE TITLE
Convert all prints to logs

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#61]
Follow up to #59 we now need to convert all the pints in the app to use the new log system that we have added.

Just use `logger.i('Text');` instead of `print('Text');` and import the logger function from 
`import package:cbj_hub/utils.dart';`

Here are the types of log that you can use
```
logger.v("Verbose log");

logger.d("Debug log");

logger.i("Info log");

logger.w("Warning log");

logger.e("Error log");

logger.wtf("What a terrible failure log");
```

**Comment by BangBuster** [comment]
#67 PR for error logs

**Comment by guyluz11** [comment]
Thanks @BangBuster is that all the prints or there are more left?

**Comment by guyluz11** [comment]
Done

Thanks @BangBuster will close this issue now.
