### ISSUE TITLE
Run dart format on incoming pull requests 

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_hub#73]
We need to find a way to run `dart format .` on incoming pull requests and commit it automatically without the intervention of the commiter.

**Comment by BangBuster** [comment]
I'll try to make it work

**Comment by guyluz11** [comment]
@BangBuster , sounds good

**Comment by guyluz11** [comment]
While formating we need to ignore the [gen](https://github.com/CyBear-Jinni/cbj_hub/tree/main/lib/infrastructure/gen) directory.

As told [here](https://github.com/dart-lang/dart_style/issues/864) you can do so with the following command (I think)

`find . -name "*.dart" ! -path '*/gen/*' | tr '\n' ' ' | xargs dart format .`
